import type { Provider, Review } from './types';

// This file contains mock data for testing purposes.
// It is used when NEXT_PUBLIC_USE_MOCK_DATA is set to 'true'.

// Helper to get a date X days ago
const daysAgo = (days: number): string => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date.toISOString();
};

export const mockProviders: Provider[] = [
    {
        id: 101,
        profile_id: 'a1',
        name: 'هنرمند برتر (زهرا)',
        service: 'طراحی ناخن',
        location: 'ارومیه',
        phone: '09111111111',
        bio: 'فعال‌ترین و بهترین هنرمند پلتفرم با بالاترین امتیاز.',
        categorySlug: 'beauty',
        serviceSlug: 'manicure-pedicure',
        rating: 4.9,
        reviewsCount: 150,
        agreements_count: 80,
        last_activity_at: daysAgo(1),
        profileImage: { src: 'https://picsum.photos/seed/101/400/400', aiHint: 'woman portrait' },
        portfolio: [{ src: 'https://picsum.photos/seed/p101/600/400', aiHint: 'nail art' }],
    },
    {
        id: 102,
        profile_id: 'a2',
        name: 'کیک‌پز محبوب (مریم)',
        service: 'کیک و شیرینی',
        location: 'ارومیه',
        phone: '09222222222',
        bio: 'امتیاز بالا، اما فعالیت اخیر کمتر از هنرمند برتر.',
        categorySlug: 'cooking',
        serviceSlug: 'cakes-sweets',
        rating: 4.9,
        reviewsCount: 120,
        agreements_count: 60,
        last_activity_at: daysAgo(10),
        profileImage: { src: 'https://picsum.photos/seed/102/400/400', aiHint: 'pastry chef' },
        portfolio: [{ src: 'https://picsum.photos/seed/p102/600/400', aiHint: 'cake design' }],
    },
    {
        id: 103,
        profile_id: 'a3',
        name: 'خیاط تازه‌کار (سارا)',
        service: 'دوخت سفارشی',
        location: 'ارومیه',
        phone: '09333333333',
        bio: 'یک هنرمند جدید با انگیزه بالا و امتیاز عالی، اما تعداد نظرات کم.',
        categorySlug: 'tailoring',
        serviceSlug: 'custom-clothing',
        rating: 5.0,
        reviewsCount: 5,
        agreements_count: 2,
        last_activity_at: daysAgo(2),
        profileImage: { src: 'https://picsum.photos/seed/103/400/400', aiHint: 'tailor woman' },
        portfolio: [],
    },
    {
        id: 104,
        profile_id: 'a4',
        name: 'سفالگر قدیمی (پروین)',
        service: 'سفال تزئینی',
        location: 'ارومیه',
        phone: '09444444444',
        bio: 'هنرمند با سابقه با تعداد توافق بالا اما امتیاز متوسط.',
        categorySlug: 'handicrafts',
        serviceSlug: 'decorative-pottery',
        rating: 4.2,
        reviewsCount: 95,
        agreements_count: 120,
        last_activity_at: daysAgo(30),
        profileImage: { src: 'https://picsum.photos/seed/104/400/400', aiHint: 'pottery artist' },
        portfolio: [{ src: 'https://picsum.photos/seed/p104/600/400', aiHint: 'pottery' }],
    },
    {
        id: 105,
        profile_id: 'a5',
        name: 'آرایشگر فعال (نیلوفر)',
        service: 'خدمات مو',
        location: 'ارومیه',
        phone: '09555555555',
        bio: 'هنرمندی با فعالیت اخیر بالا که او را در لیست بالا می‌آورد.',
        categorySlug: 'beauty',
        serviceSlug: 'haircut-coloring',
        rating: 4.6,
        reviewsCount: 45,
        agreements_count: 25,
        last_activity_at: daysAgo(0), // Active today!
        profileImage: { src: 'https://picsum.photos/seed/105/400/400', aiHint: 'woman hair' },
        portfolio: [],
    },
    {
        id: 106,
        profile_id: 'a6',
        name: 'نانوای خانگی (الهام)',
        service: 'نان خانگی',
        location: 'ارومیه',
        phone: '09666666666',
        bio: 'امتیاز متوسط اما نظرات و توافق‌های رو به رشد.',
        categorySlug: 'cooking',
        serviceSlug: 'homemade-bread',
        rating: 4.5,
        reviewsCount: 30,
        agreements_count: 15,
        last_activity_at: daysAgo(5),
        profileImage: { src: 'https://picsum.photos/seed/106/400/400', aiHint: 'baker woman' },
        portfolio: [{ src: 'https://picsum.photos/seed/p106/600/400', aiHint: 'bread' }],
    },
    {
        id: 107,
        profile_id: 'a7',
        name: 'بوتیک شیک (افسانه)',
        service: 'مزون',
        location: 'ارومیه',
        phone: '09777777777',
        bio: 'یک هنرمند بسیار قدیمی که دیگر فعال نیست و باید در انتهای لیست باشد.',
        categorySlug: 'tailoring',
        serviceSlug: 'fashion-design-mezon',
        rating: 4.8,
        reviewsCount: 200,
        agreements_count: 150,
        last_activity_at: daysAgo(200), // Very old activity
        profileImage: { src: 'https://picsum.photos/seed/107/400/400', aiHint: 'fashion boutique' },
        portfolio: [],
    },
    {
        id: 108,
        profile_id: 'a8',
        name: 'جواهرات خاص (گیتا)',
        service: 'زیورآلات دست‌ساز',
        location: 'ارومیه',
        phone: '09888888888',
        bio: 'امتیاز عالی، فعالیت اخیر، اما تعداد نظرات کم.',
        categorySlug: 'handicrafts',
        serviceSlug: 'handmade-jewelry',
        rating: 4.9,
        reviewsCount: 15,
        agreements_count: 10,
        last_activity_at: daysAgo(3),
        profileImage: { src: 'https://picsum.photos/seed/108/400/400', aiHint: 'jewelry maker' },
        portfolio: [],
    },
    {
        id: 109,
        profile_id: 'a9',
        name: 'هنرمند بدون فعالیت',
        service: 'اپیلاسیون',
        location: 'ارومیه',
        phone: '09999999999',
        bio: 'این هنرمند هیچ فعالیتی ثبت نکرده و باید در انتهای لیست باشد.',
        categorySlug: 'beauty',
        serviceSlug: 'waxing',
        rating: 4.0,
        reviewsCount: 10,
        agreements_count: 5,
        last_activity_at: null, // No activity
        profileImage: { src: 'https://picsum.photos/seed/109/400/400', aiHint: 'woman' },
        portfolio: [],
    },
    {
        id: 110,
        profile_id: 'a10',
        name: 'آشپز معمولی (لیلا)',
        service: 'غذای سنتی',
        location: 'ارومیه',
        phone: '09101010101',
        bio: 'همه فاکتورهایش متوسط است.',
        categorySlug: 'cooking',
        serviceSlug: 'traditional-food',
        rating: 4.4,
        reviewsCount: 55,
        agreements_count: 33,
        last_activity_at: daysAgo(45),
        profileImage: { src: 'https://picsum.photos/seed/110/400/400', aiHint: 'woman cooking' },
        portfolio: [],
    },
];


export const mockReviews: Review[] = [
    { id: 'r1', provider_id: 'a1', author_id: 'c1', authorName: 'مشتری ۱', rating: 5, comment: 'کارشون بی‌نظیره! واقعاً حرفه‌ای و با دقت.', createdAt: daysAgo(2) },
    { id: 'r2', provider_id: 'a1', author_id: 'c2', authorName: 'مشتری ۲', rating: 4, comment: 'خیلی خوب بود، فقط کمی تاخیر داشتند.', createdAt: daysAgo(5) },
    { id: 'r3', provider_id: 'a2', author_id: 'c3', authorName: 'مشتری ۳', rating: 5, comment: 'کیک تولد پسرم عالی بود، همه خوششون اومد.', createdAt: daysAgo(11) },
    { id: 'r4', provider_id: 'a3', author_id: 'c4', authorName: 'مشتری ۴', rating: 5, comment: 'خیلی با حوصله و دقیق لباس رو دوختن. ممنونم!', createdAt: daysAgo(3) },
    { id: 'r5', provider_id: 'a4', author_id: 'c5', authorName: 'مشتری ۵', rating: 3, comment: 'کیفیت کار خوب بود اما زمان تحویل خیلی طولانی شد.', createdAt: daysAgo(40) },
];
