-- Banoutik Schema v3 (Final)
-- This script will completely reset and set up the necessary tables, policies, and triggers for the Banoutik app.
-- It is designed to be run in its entirety and is safe to re-run.

-- 1. Drop dependent objects first
DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users";
DROP FUNCTION IF EXISTS "public"."handle_new_user"();

-- 2. Drop all tables
-- The CASCADE option automatically drops dependent objects like policies.
DROP TABLE IF EXISTS "public"."reviews" CASCADE;
DROP TABLE IF EXISTS "public"."one_time_passwords" CASCADE;
DROP TABLE IF EXISTS "public"."profiles" CASCADE;
DROP TABLE IF EXISTS "public"."services" CASCADE;
DROP TABLE IF EXISTS "public"."categories" CASCADE;


-- 3. Create tables in the correct order of dependency

-- Create the categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT
);
COMMENT ON TABLE public.categories IS 'Stores the main service categories for Banoutik.';

-- Create the services table
CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES public.categories(id),
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    UNIQUE(slug, category_id)
);
COMMENT ON TABLE public.services IS 'Stores the specific services offered within each category.';

-- Create the profiles table
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    account_type TEXT NOT NULL CHECK (account_type IN ('customer', 'provider')),
    full_name TEXT,
    phone TEXT UNIQUE,
    -- Provider-specific fields (nullable)
    bio TEXT,
    location TEXT,
    service_id BIGINT REFERENCES public.services(id),
    profile_image_url TEXT,
    rating NUMERIC(2, 1) DEFAULT 0.0,
    reviews_count INT DEFAULT 0
);
COMMENT ON TABLE public.profiles IS 'Stores public profile information for all users (customers and providers).';

-- Create the one_time_passwords table
CREATE TABLE public.one_time_passwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL UNIQUE,
    token TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.one_time_passwords IS 'Stores OTPs for phone verification.';

-- Create the reviews table
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_author CHECK (author_id <> provider_id)
);
COMMENT ON TABLE public.reviews IS 'Stores reviews written by customers for providers.';


-- 4. Enable Row Level Security (RLS) for all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.one_time_passwords ENABLE ROW LEVEL SECURITY; -- Security on OTP is important

-- 5. Create Security Policies

-- Allow public read access for categories and services
CREATE POLICY "Allow public read access to categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access to services" ON public.services FOR SELECT USING (true);

-- Allow public read access for profiles
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);

-- Allow users to update their own profile
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Allow public read access for reviews
CREATE POLICY "Allow public read access to reviews" ON public.reviews FOR SELECT USING (true);

-- Allow authenticated users to insert reviews
CREATE POLICY "Allow authenticated users to insert reviews" ON public.reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- 6. Create Triggers and Functions

-- Function to create a new profile for each new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, phone, full_name, account_type)
  VALUES (
    new.id,
    new.phone,
    new.raw_user_meta_data->>'full_name',
    COALESCE(new.raw_user_meta_data->>'account_type', 'customer')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
COMMENT ON FUNCTION public.handle_new_user() IS 'Automatically creates a profile entry when a new user signs up in auth.users.';


-- Trigger to call the function when a new user is created
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Grant usage on schema to postgres and anon roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;

-- Grant all privileges to the postgres role
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, service_role;

-- Grant select privileges to the anon and authenticated roles
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to anon, authenticated;
