-- 1. Create the messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT NOT NULL,
    sender_id UUID REFERENCES auth.users(id),
    receiver_id UUID REFERENCES auth.users(id),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS policies
-- Users can see messages they have sent or received.
CREATE POLICY "Users can view their own messages"
ON public.messages
FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- Users can insert their own messages.
CREATE POLICY "Users can insert their own messages"
ON public.messages
FOR INSERT
WITH CHECK (auth.uid() = sender_id);

-- 4. Set up the table for realtime
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- 5. Create the function to get user conversations
CREATE OR REPLACE FUNCTION get_user_conversations(p_user_id UUID)
RETURNS TABLE (
    chat_id TEXT,
    other_user_id UUID,
    other_user_name TEXT,
    other_user_phone TEXT,
    last_message_content TEXT,
    last_message_at TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH ranked_messages AS (
        SELECT
            m.chat_id,
            m.sender_id,
            m.receiver_id,
            m.content,
            m.created_at,
            ROW_NUMBER() OVER(PARTITION BY m.chat_id ORDER BY m.created_at DESC) as rn
        FROM
            messages m
        WHERE
            m.sender_id = p_user_id OR m.receiver_id = p_user_id
    ),
    last_messages AS (
        SELECT
            rm.chat_id,
            rm.content AS last_message_content,
            rm.created_at AS last_message_at,
            CASE
                WHEN rm.sender_id = p_user_id THEN rm.receiver_id
                ELSE rm.sender_id
            END AS other_user_id
        FROM
            ranked_messages rm
        WHERE
            rm.rn = 1
    )
    SELECT
        lm.chat_id,
        lm.other_user_id,
        COALESCE(p.name, c.name, 'کاربر حذف شده') AS other_user_name,
        COALESCE(p.phone, c.phone) AS other_user_phone,
        lm.last_message_content,
        lm.last_message_at
    FROM
        last_messages lm
    LEFT JOIN
        providers p ON lm.other_user_id = p.user_id
    LEFT JOIN
        customers c ON lm.other_user_id = c.user_id
    ORDER BY
        lm.last_message_at DESC;
END;
$$;
