
-- Create a custom type for user account types to ensure data integrity.
CREATE TYPE public.user_account_type AS ENUM ('provider', 'customer');

-- Create the main users table, referencing the custom type.
-- This table stores universal information for all users.
CREATE TABLE public.users (
    id uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    phone text NOT NULL UNIQUE,
    account_type public.user_account_type NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the providers table for users who offer services.
-- It links to the users table via a foreign key.
CREATE TABLE public.providers (
    id bigint PRIMARY KEY generated by default as identity,
    user_id uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text NOT NULL UNIQUE,
    service text NOT NULL,
    location text NOT NULL,
    bio text NOT NULL,
    category_slug text NOT NULL,
    service_slug text NOT NULL,
    rating real NOT NULL DEFAULT 0,
    reviews_count integer NOT NULL DEFAULT 0,
    profile_image jsonb,
    portfolio jsonb[],
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the customers table for users who consume services.
-- This table is simple and links to the users table.
CREATE TABLE public.customers (
    id bigint PRIMARY KEY generated by default as identity,
    user_id uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the reviews table.
-- It links to both providers and users (customers).
CREATE TABLE public.reviews (
    id bigint PRIMARY KEY generated by default as identity,
    provider_id bigint NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
    customer_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    customer_name text NOT NULL
);

-- Create the agreements table.
CREATE TABLE public.agreements (
    id bigint PRIMARY KEY generated by default as identity,
    customer_phone text NOT NULL,
    provider_phone text NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed')),
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    confirmed_at timestamp with time zone
);

-- Create the conversations table.
CREATE TABLE public.conversations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_one_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    participant_two_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_message_at timestamp with time zone
);

-- Create the messages table.
CREATE TABLE public.messages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    receiver_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    content text NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
