-- First, create the custom ENUM type for user roles.
-- This ensures the type exists before it's referenced by the 'users' table.
CREATE TYPE public.user_account_type AS ENUM ('customer', 'provider');

-- Create the users table, referencing the custom type.
CREATE TABLE public.users (
    id uuid NOT NULL PRIMARY KEY,
    name text NOT NULL,
    phone text NOT NULL UNIQUE,
    account_type public.user_account_type NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the providers table with a foreign key to the users table.
CREATE TABLE public.providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text NOT NULL UNIQUE,
    service text NOT NULL,
    location text NOT NULL,
    bio text NOT NULL,
    category_slug text NOT NULL,
    service_slug text NOT NULL,
    rating real NOT NULL DEFAULT 0,
    reviews_count integer NOT NULL DEFAULT 0,
    profile_image jsonb NOT NULL,
    portfolio jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the customers table with a foreign key to the users table.
CREATE TABLE public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create the reviews table with foreign keys.
CREATE TABLE public.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
    customer_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    customer_name text NOT NULL
);

-- Create the agreements table with a CHECK constraint using correct syntax.
CREATE TABLE public.agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_phone text NOT NULL,
    provider_phone text NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed')),
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    confirmed_at timestamp with time zone
);
