create table
  public.customers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    phone text not null,
    "accountType" text not null default 'customer'::text,
    constraint customers_pkey primary key (id),
    constraint customers_phone_key unique (phone)
  ) tablespace pg_default;