
-- Create the customers table
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    phone text NOT NULL UNIQUE,
    account_type text DEFAULT 'customer'::text NOT NULL
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.customers IS 'Stores customer user data.';
COMMENT ON COLUMN public.customers.name IS 'Full name of the customer.';
COMMENT ON COLUMN public.customers.phone IS 'Unique phone number for the customer, used for login.';
COMMENT ON COLUMN public.customers.account_type IS 'The type of user account, always ''customer''.';

-- Enable Row Level Security (RLS) for the customers table
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public (unauthenticated) users to create a new customer record (i.e., sign up)
CREATE POLICY "Allow public inserts for customers"
ON public.customers
FOR INSERT
WITH CHECK (true);

-- Create a policy to allow all users (authenticated or not) to read customer data.
-- This is necessary for the login process to check if a user exists.
CREATE POLICY "Enable read access for all users"
ON public.customers
FOR SELECT
USING (true);
