-- Create the 'customers' table to store user data.
CREATE TABLE
  customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    account_type TEXT DEFAULT 'customer' NOT NULL
  );

-- Add comments to columns for clarity.
COMMENT ON TABLE customers IS 'Stores customer user information.';
COMMENT ON COLUMN customers.name IS 'The full name of the customer.';
COMMENT ON COLUMN customers.phone IS 'The unique phone number for the customer, used for login.';

-- Enable Row Level Security for the 'customers' table.
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to create a new customer account (for registration).
CREATE POLICY "Allow public insert for new customers" ON customers
FOR INSERT
WITH CHECK (TRUE);

-- Create a policy to allow anyone to read customer data (for login checks).
CREATE POLICY "Allow public read access to customers" ON customers
FOR SELECT
USING (TRUE);
