
create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null unique,
    account_type text not null default 'customer',
    created_at timestamp with time zone not null default now()
);
