
-- This script creates the agreements table to track service agreements
-- between customers and providers.

CREATE TABLE agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_phone TEXT NOT NULL,
    provider_phone TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    confirmed_at TIMESTAMP WITH TIME ZONE
);

-- Add a check constraint for the status column
ALTER TABLE agreements ADD CONSTRAINT check_agreement_status CHECK (status IN ('pending', 'confirmed'));

-- Add policies for row-level security
-- Allow users to see agreements they are part of
CREATE POLICY "Allow users to see their own agreements"
ON agreements FOR SELECT
USING (
  (SELECT auth.uid()::text) IN (customer_phone, provider_phone)
);

-- Allow customers to create agreements for themselves
CREATE POLICY "Allow customers to create agreements"
ON agreements FOR INSERT
WITH CHECK (
  auth.role() = 'authenticated' AND
  (SELECT auth.uid()::text) = customer_phone
);

-- Allow providers to update the status of their agreements
CREATE POLICY "Allow providers to confirm agreements"
ON agreements FOR UPDATE
USING (
  auth.role() = 'authenticated' AND
  (SELECT auth.uid()::text) = provider_phone
);
