-- 1. Create the agreements table
CREATE TABLE agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "providerPhone" text NOT NULL,
    "customerPhone" text NOT NULL,
    "customerName" text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    requested_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "confirmedAt" timestamp with time zone
);

-- 2. Enable Row Level Security
ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for providers
CREATE POLICY "Allow provider to read their agreements"
ON public.agreements
FOR SELECT TO authenticated
USING (
    "providerPhone" = (auth.jwt() ->> 'phone')
);

CREATE POLICY "Allow provider to update their agreements"
ON public.agreements
FOR UPDATE TO authenticated
USING (
    "providerPhone" = (auth.jwt() ->> 'phone')
);


-- 4. Create policies for customers
CREATE POLICY "Allow customer to insert agreements"
ON public.agreements
FOR INSERT TO authenticated
WITH CHECK (
    "customerPhone" = (auth.jwt() ->> 'phone')
);

CREATE POLICY "Allow customer to read their own agreements"
ON public.agreements
FOR SELECT TO authenticated
USING (
    "customerPhone" = (auth.jwt() ->> 'phone')
);
