create table
  public.customers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    phone character varying not null,
    account_type character varying not null default 'customer'::character varying,
    constraint customers_pkey primary key (id),
    constraint customers_phone_key unique (phone)
  ) tablespace pg_default;
