
-- supabase/migrations/YYYYMMDDHHMMSS_create_agreements_table.sql

-- Enable pgcrypto extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the agreements table
CREATE TABLE IF NOT EXISTS public.agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_phone TEXT NOT NULL,
    provider_phone TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- e.g., 'pending', 'confirmed', 'rejected'
    requested_at timestamp with time zone DEFAULT now() NOT NULL,
    confirmed_at timestamp with time zone
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.agreements IS 'Tracks service agreements between customers and providers.';
COMMENT ON COLUMN public.agreements.id IS 'Unique identifier for the agreement.';
COMMENT ON COLUMN public.agreements.customer_phone IS 'The phone number of the customer requesting the service.';
COMMENT ON COLUMN public.agreements.provider_phone IS 'The phone number of the provider offering the service.';
COMMENT ON COLUMN public.agreements.status IS 'The current status of the agreement (e.g., pending, confirmed).';
COMMENT ON COLUMN public.agreements.requested_at IS 'Timestamp of when the customer made the request.';
COMMENT ON COLUMN public.agreements.confirmed_at IS 'Timestamp of when the provider confirmed the agreement.';

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_agreements_customer_phone ON public.agreements(customer_phone);
CREATE INDEX IF NOT EXISTS idx_agreements_provider_phone ON public.agreements(provider_phone);
