
-- Create the customers table
create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  account_type text not null default 'customer',
  created_at timestamp with time zone not null default now()
);

-- Enable Row Level Security
alter table public.customers enable row level security;

-- Create policy to allow public inserts for new customer registrations
create policy "Allow public inserts for new customers"
  on public.customers
  for insert
  with check (true);

-- Create policy to allow users to view their own customer data
create policy "Enable read access for all users"
  on public.customers
  for select
  using (true);
