-- Create the customers table
create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    phone text not null,
    "accountType" text not null default 'customer'::text,
    constraint customers_phone_key unique (phone)
);

-- Enable Row Level Security
alter table public.customers enable row level security;

-- Create policies for customers table
-- Allow users to read their own customer entry
create policy "Users can view their own customer data."
on public.customers for select
using ( auth.uid()::text = phone );

-- Allow users to create their own customer entry
create policy "Users can create their own customer entry."
on public.customers for insert
with check ( auth.uid()::text = phone );
