-- Create the customers table to store user information
create table
  public.customers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    phone text not null,
    account_type text not null default 'customer'::text,
    constraint customers_pkey primary key (id),
    constraint customers_phone_key unique (phone)
  ) tablespace pg_default;

-- Enable Row Level Security (RLS) for the new table
alter table public.customers enable row level security;

-- Create a policy to allow public (unauthenticated) users to create a new customer record.
-- This is essential for the registration process to work.
create policy "Allow public inserts for new customers" on public.customers for
insert
  with check (true);

-- Create a policy to allow public (unauthenticated) users to read customer records.
-- This is essential for the login process to check if a user exists.
create policy "Enable read access for all users" on public.customers for
select
  using (true);
