-- 1. Create the agreements table
CREATE TABLE agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    providerPhone text NOT NULL,
    customerPhone text NOT NULL,
    customerName text NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    requested_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    confirmedAt timestamp with time zone
);

-- 2. Enable Row Level Security
ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for the agreements table

-- Allow providers to view their own agreements
CREATE POLICY "Enable read access for provider"
ON public.agreements
FOR SELECT
USING (auth.jwt() ->> 'phone' = providerPhone);

-- Allow authenticated users to create new agreements
CREATE POLICY "Enable insert for authenticated users"
ON public.agreements
FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Allow providers to update their own agreements (to confirm them)
CREATE POLICY "Enable update for provider"
ON public.agreements
FOR UPDATE
USING (auth.jwt() ->> 'phone' = providerPhone);

-- NEW: Allow customers to view their own agreements
CREATE POLICY "Enable read access for customer"
ON public.agreements
FOR SELECT
USING (auth.jwt() ->> 'phone' = customerPhone);
