
-- Create the customers table
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying,
    phone character varying NOT NULL,
    account_type character varying NOT NULL DEFAULT 'customer'::character varying,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_phone_key UNIQUE (phone)
);

-- Enable Row Level Security for the new table
ALTER TABLE IF EXISTS public.customers
    ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public inserts (for registration)
CREATE POLICY "Allow public insert for customers"
    ON public.customers
    FOR INSERT
    TO public
    WITH CHECK (true);

-- Create policy to allow all users to read customer data (for login checks, etc.)
CREATE POLICY "Enable read access for all users on customers"
    ON public.customers
    FOR SELECT
    TO public
    USING (true);
